Per #636, updates to the Dockerfile and build script.

diff --git a/ci/docker/docker_data/Dockerfile b/ci/docker/docker_data/Dockerfile
--- a/ci/docker/docker_data/Dockerfile
+++ b/ci/docker/docker_data/Dockerfile
@@ -1,31 +1,45 @@
 FROM centos:7
 MAINTAINER George McCabe <mccabe@ucar.edu>
 
-# Required arguments
-ARG TARFILE
+# Required argument
+ARG TARFILE_URL
+
+# Optional argument
 ARG MOUNTPT
 
-# Check that TARFILE is defined.
-RUN if [ "x${TARFILE}" == "x" ]; then \
-      echo "ERROR: TARFILE undefined! Rebuild with \"--build-arg TARFILE={One or more input tarfiles}\""; \
-      exit 1; \
-    fi
-
-# Check that MOUNTPT is defined.
-RUN if [ "x${MOUNTPT}" == "x" ]; then \
-      echo "ERROR: MOUNTPT undefined! Rebuild with \"--build-arg MOUNTPT={Mount point directory}\""; \
+# Check that TARFILE_URL is defined.
+RUN if [ "x${TARFILE_URL}" == "x" ]; then \
+      echo "ERROR: TARFILE_URL undefined! Rebuild with \"--build-arg TARFILE_URL={One or more URL's}\""; \
       exit 1; \
     fi
 
 ENV CASE_DIR /data/input/METplus_Data
 RUN mkdir -p ${CASE_DIR}
 
-RUN for CUR_TARFILE in `echo ${TARFILE} | tr "," " "`; do \
-      echo "Downloading: ${CUR_TARFILE}"; \
-      curl -SL https://dtcenter.ucar.edu/dfiles/code/METplus/METplus_Data/${CUR_TARFILE} | tar -xzC ${CASE_DIR}; \
+RUN for URL in `echo ${TARFILE_URL} | tr "," " "`; do \
+      echo "Downloading: ${URL}"; \
+      curl -SL ${URL} | tar -xzC ${CASE_DIR}; \
     done
 
-VOLUME ${MOUNTPT}
+# Check that .VOLUME exists, if necessary.
+RUN if [ "x${MOUNTPT}" == "x" ]; then \
+      VOLUME_FILE=`find /data/input/METplus_Data -name .VOLUME | head -1`; \
+      if [ "x${VOLUME_FILE}" == "x" ]; then \
+        echo "ERROR: Required .VOLUME file not found!"; \
+        exit 1; \
+      fi; \
+      MOUNTPT=`dirname ${VOLUME_FILE}`; \
+    fi; \
+    echo "Mounting directory: ${MOUNTPT}"
+
+# Define the volume mount point
+VOLUME if [ "x${MOUNTPT}" == "x" ]; then \
+         VOLUME_FILE=`find /data/input/METplus_Data -name .VOLUME | head -1`; \
+         echo `dirname ${VOLUME_FILE}`; \
+       else; \
+         echo ${MOUNTPT}; \
+       fi
+
 USER root
 CMD ["true"]
 
