Per #636, we had lots of trouble getting the multiple data volumes to work well together. Turns out the issue was in setting the VOLUME mount in the Dockerfile. While we were able to deteremine the desired directory to mount in a Docker RUN command, we were not able to use that to set the value for VOLUME. I read up about it and tried several things but nothing worked. Instead, I modified the Dockerfile to make MOUNTPT a required input argument. And I enhanced the build_docker_images.sh script pull a file from the website which defines the volume mount directories for each dataset version.

diff --git a/ci/docker/docker_data/Dockerfile b/ci/docker/docker_data/Dockerfile
--- a/ci/docker/docker_data/Dockerfile
+++ b/ci/docker/docker_data/Dockerfile
@@ -1,10 +1,8 @@
 FROM centos:7
 MAINTAINER George McCabe <mccabe@ucar.edu>
 
-# Required argument
+# Required arguments
 ARG TARFILE_URL
-
-# Optional argument
 ARG MOUNTPT
 
 # Check that TARFILE_URL is defined.
@@ -13,7 +11,13 @@ RUN if [ "x${TARFILE_URL}" == "x" ]; then \
       exit 1; \
     fi
 
-ENV CASE_DIR /data/input/METplus_Data
+# Check that MOUNTPT is defined.
+RUN if [ "x${MOUNTPT}" == "x" ]; then \
+      echo "ERROR: MOUNTPT undefined! Rebuild with \"--build-arg MOUNTPT={VOLUME mount directory}\""; \
+      exit 1; \
+    fi
+
+ENV CASE_DIR=/data/input/METplus_Data
 RUN mkdir -p ${CASE_DIR}
 
 RUN for URL in `echo ${TARFILE_URL} | tr "," " "`; do \
@@ -21,24 +25,8 @@ RUN for URL in `echo ${TARFILE_URL} | tr "," " "`; do \
       curl -SL ${URL} | tar -xzC ${CASE_DIR}; \
     done
 
-# Check that .VOLUME exists, if necessary.
-RUN if [ "x${MOUNTPT}" == "x" ]; then \
-      VOLUME_FILE=`find /data/input/METplus_Data -name .VOLUME | head -1`; \
-      if [ "x${VOLUME_FILE}" == "x" ]; then \
-        echo "ERROR: Required .VOLUME file not found!"; \
-        exit 1; \
-      fi; \
-      MOUNTPT=`dirname ${VOLUME_FILE}`; \
-    fi; \
-    echo "Mounting directory: ${MOUNTPT}"
-
 # Define the volume mount point
-VOLUME if [ "x${MOUNTPT}" == "x" ]; then \
-         VOLUME_FILE=`find /data/input/METplus_Data -name .VOLUME | head -1`; \
-         echo `dirname ${VOLUME_FILE}`; \
-       else; \
-         echo ${MOUNTPT}; \
-       fi
+VOLUME ${MOUNTPT}
 
 USER root
 CMD ["true"]
