error if MET_BRANCH was not passed to build command

diff --git a/internal_tests/docker/Dockerfile b/internal_tests/docker/Dockerfile
--- a/internal_tests/docker/Dockerfile
+++ b/internal_tests/docker/Dockerfile
@@ -3,8 +3,6 @@ ARG MET_BRANCH
 FROM dtcenter/met:${MET_BRANCH:-develop}
 MAINTAINER George McCabe <mccabe@ucar.edu>
 
-ARG MET_BRANCH
-RUN echo ${MET_BRANCH}
 # 
 # This Dockerfile extends the MET image file to run METplus
 #
@@ -26,7 +24,8 @@ ARG MET_BRANCH
 # MET_BRANCH is not defined when built via Docker Hub.
 #
 RUN if [ -z ${MET_BRANCH+x} ]; then \
-      echo "WARNING: MET_BRANCH undefined! Using default (develop) or rebuild with \"--build-arg MET_BRANCH={branch name}\""; \
+      echo "ERROR: MET_BRANCH undefined! Using default (develop) or rebuild with \"--build-arg MET_BRANCH={branch name}\""; \
+      exit 1; \
     else \
       echo "Build Argument MET_BRANCH=${MET_BRANCH}"; \
     fi
