Feature 498 master v3.0 docker (#528)
* added clone of METplus repo and replace MET_INSTALL_DIR with correct path

* added build hook for docker file to set correct MET branch to use

diff --git a/internal_tests/docker/Dockerfile b/internal_tests/docker/Dockerfile
--- a/internal_tests/docker/Dockerfile
+++ b/internal_tests/docker/Dockerfile
@@ -1,9 +1,29 @@
-FROM dtcenter/met:master_v9.0
+ARG MET_BRANCH
+
+FROM dtcenter/met:${MET_BRANCH:-develop}
 MAINTAINER George McCabe <mccabe@ucar.edu>
 
 # 
 # This Dockerfile extends the MET image file to run METplus
 #
+
+ARG SOURCE_BRANCH
+
+RUN if [ -z ${SOURCE_BRANCH+x} ]; then \
+      echo "ERROR: SOURCE_BRANCH undefined! Rebuild with \"--build-arg SOURCE_BRANCH={branch name}\""; \
+      exit 1; \
+    else \
+      echo "Build Argument SOURCE_BRANCH=${SOURCE_BRANCH}"; \
+    fi
+
+ARG MET_BRANCH
+
+RUN if [ -z ${MET_BRANCH+x} ]; then \
+      echo "ERROR: MET_BRANCH undefined! Using default (develop) or rebuild with \"--build-arg MET_BRANCH={branch name}\""; \
+      exit 1; \
+    else \
+      echo "Build Argument MET_BRANCH=${MET_BRANCH}"; \
+    fi
 
 #
 # Set working directory
@@ -45,10 +65,6 @@ RUN echo export PATH=$PATH:/metplus/METplus/ush >> /etc/bashrc \
 # && echo export METPLUS_DISABLE_PLOT_WRAPPERS=yes >> /etc/bashrc \
 # && echo setenv METPLUS_DISABLE_PLOT_WRAPPERS yes >> /etc/csh.cshrc
 ENV METPLUS_DISABLE_PLOT_WRAPPERS yes
-#ENV PYTHONPATH /metplus/METplus/ush
-
-#PATH=$PATH:/new/path/bin
-#ENV PATH "$PATH:/metplus/METplus/ush"
 
 #
 # Install required packages: Pandas, Cartopy*
@@ -63,3 +79,14 @@ RUN yum -y update \
  && python3 -m pip install pytest
 
 
+ARG SOURCE_BRANCH
+
+# if SOURCE_BRANCH is not develop, clone the repository using the branch
+# also replace MET_INSTALL_DIR value in default conf with correct location
+RUN if [ ${SOURCE_BRANCH} != "develop" ]; then \
+      echo "Cloning METplus repository with -b ${SOURCE_BRANCH}"; \
+      git clone https://github.com/NCAR/METplus; \
+      cd METplus; \
+      git checkout ${SOURCE_BRANCH}; \
+      sed -i 's|MET_INSTALL_DIR = /path/to|MET_INSTALL_DIR = /usr/local|g' parm/metplus_config/metplus_system.conf; \
+   fi
