Per #589, update the Docker data setup to explicitly define the mount point directory for each tarball so that you can mount multiple ones in a docker run command without them clobbering eachother.

diff --git a/internal_tests/docker_data/Dockerfile b/internal_tests/docker_data/Dockerfile
--- a/internal_tests/docker_data/Dockerfile
+++ b/internal_tests/docker_data/Dockerfile
@@ -4,6 +4,7 @@ MAINTAINER George McCabe <mccabe@ucar.edu>
 # Required arguments
 ARG VERSION
 ARG TARFILE
+ARG MOUNTPT
 
 # Check that VERSION is defined.
 RUN if [ "x${VERSION}" == "x" ]; then \
@@ -17,12 +18,18 @@ RUN if [ "x${TARFILE}" == "x" ]; then \
       exit 1; \
     fi
 
+# Check that MOUNTPT is defined.
+RUN if [ "x${MOUNTPT}" == "x" ]; then \
+      echo "ERROR: MOUNTPT undefined! Rebuild with \"--build-arg MOUNTPT={Mount point directory}\""; \
+      exit 1; \
+    fi
+
 ENV CASE_DIR /data/input/METplus_Data
 RUN mkdir -p ${CASE_DIR}
 
 RUN curl -SL https://github.com/dtcenter/METplus/releases/download/${VERSION}/${TARFILE} | tar -xzC ${CASE_DIR}
 
-VOLUME $CASE_DIR
+VOLUME ${MOUNTPT}
 USER root
 CMD ["true"]
 
