only run error log merge step if there were 'Save error logs' jobs that succeeded

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -230,12 +230,26 @@ jobs:
           path: artifact/diff-${{ steps.get-artifact-name.outputs.artifact_name }}
           if-no-files-found: ignore
 
-  merge:
+  merge_error_logs:
+    name: Merge Error Logs
     runs-on: ubuntu-latest
     needs: use_case_tests
-    if: ${{ always() }}
+    if: ${{ always() && needs.use_case_tests.result == 'failure' }}
     steps:
+      - name: Check for error logs
+        id: check-for-error-logs
+        continue-on-error: true
+        run: |
+          json_data=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
+                 "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs")
+          error_log_jobs=($(echo "$json_data" | jq -r '.jobs[] | select(.name | startswith("Use Case Tests")) | .steps[] | select(.name | startswith("Save error logs")) | select(.conclusion | startswith("success"))'))
+          # if no error logs were created, exit non-zero (fail) to skip merge
+          if [ -z "${error_log_jobs}" ]; then
+            exit 1
+          fi
+
       - name: Merge Artifacts
+        if: ${{ always() && steps.check-for-error-logs.conclusion != 'success' }}
         uses: actions/upload-artifact/merge@v4
         with:
           name: error_logs
